### ISSUE TITLE
Unable to build Android project after upgrading to 16.3.5 - Java.Interop version mismatch

### ISSUE THREAD

**Issue by ryanholden8** [reactiveui/ReactiveUI#2994]
**Describe the bug**
Was on ReactiveUI 16.2.6. When upgrading to 16.3.5 this error is given when compiling/building the Android project.

> Error CS1705: Assembly 'ReactiveUI' with identity 'ReactiveUI, Version=16.3.0.0, Culture=neutral, PublicKeyToken=null' uses 'Java.Interop, Version=0.1.2.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' which has a higher version than referenced assembly 'Java.Interop' with identity 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' (CS1705) (Droid)

The .NET standard projects that have been upgraded to ReactiveUI 16.3.5 compile fine.

**Steps To Reproduce**
1. Upgrade from ReactiveUI 16.2.6 to 16.3.5 in an Android project.
2. Compile Android project
3. Wish I could provide more context but not sure what the error even means. Please let me know what I could do to help diagnose.

**Environment**
- OS:  Android
- Target Framework: 11.0 (R) API level 30
- ReactiveUI Version: 16.3.5
- IDE: VS 8.10.11 on MacOS 11.6

**Comment by glennawatson** [comment]
Weird one. Will have to look into it in the morning.

**Comment by ryanholden8** [comment]
@glennawatson Appreciate it!

Attached an isolated project that somewhat reproduces the issue. Interestingly it's only a warning in the isolated project. In our main project we have the same warning and a separate build error with the same main message as the warning. We do not have warnings as error turned on.

[ReactiveUI16.3.5Test.zip](https://github.com/reactiveui/ReactiveUI/files/7461196/ReactiveUI16.3.5Test.zip)

**Comment by gerardvanderkruijs** [comment]
Same issue here, thanks for reporting this one @ryanholden8 👍
I will keep an eye on this thread and thanks in advance for looking into it!

**Comment by glennawatson** [comment]
Related to https://github.com/xamarin/xamarin-android/issues/6438

**Comment by glennawatson** [comment]
@ryanholden8 I'm applying his fix to our build which should eliminate the newer Java.Interop being applied.

**Comment by ryanholden8** [comment]
@glennawatson You da the man, thank you!

**Comment by glennawatson** [comment]
Ok, false start but the real fix should be there now.  in 16.3.9

**Comment by gerardvanderkruijs** [comment]
Hi @glennawatson ,
Thanks again for looking into this issue so fast!

I just updated the `ReactiveUI` packages to v16.3.9, but unfortunately this didn't fix it for me, the error is still there.
@ryanholden8 , did the update fix it in for you in your project or do you also still have the error?

**Comment by glennawatson** [comment]
I will reach out to the visual studio team and see what more we can do. Seems like the official fix is only days away anyway

**Comment by ryanholden8** [comment]
@gerardvanderkruijs Updating to 16.3.10 did seem to work ok. I also upgraded to 16.3.10 in the isolated project I attached above and the warning did go away after updating to 16.3.10.

**Comment by gerardvanderkruijs** [comment]
Ah nice @ryanholden8 ! Gonna check it tomorrow, thanks for the update.
Also thank you again @glennawatson 🙌
