### ISSUE TITLE
[BUG][Uno][Mobile][net6.0-macos] Generator errors after upgrade from 14.3.10 to 15.1.1

### ISSUE THREAD

**Issue by HavenDV** [reactiveui/ReactiveUI#2915]
**Describe the bug**
Exceptions like this only for `net6.0-macos` platform(`net6.0-android`, `net6.0-ios`, `net6.0-maccatalyst` works):
```
C:\Users\haven\source\repos\DedooseV2\Dedoose.Apps\src\apps\Dedoose.Apps.Uno.Mobile\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.NativeCtor.NativeCtorsGenerator\Dedoose.Views.ExportDescriptorsViewBase_7d9b55426e189b4ea74c76c7bebda288.cs(41,53,41,57): error CS1729: 'ReactiveUserControl<ExportDescriptorsViewModel>' does not contain a constructor that takes 1 arguments
```
where Base classes like:
```cs
public abstract partial class DescriptorsViewBase :
    ReactiveUI.Uno.ReactiveUserControl<DescriptorsViewModel>
{
}
```
**Environment**
- ReactiveUI Version:    15.1.1
- Uno Version:    3.10.0-dev.554

**Comment by glennawatson** [comment]
We don't control the source generator for UNO so closing this one regardless.
